version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y expect
      - expect -c " ; spawn passwd irc ; expect \"Enter new UNIX password:\" ; send -- \"hogefuga\n\" ; expect \"Retype new UNIX password:\" ; send \"hogefuga\n\" ; expect \"password updated successfully\" ; send \"exit\n\" ;"
