version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install -y expect
      - expect  -c " ; set timeout -1 ; spawn passwd irc ; expect \"Enter new UNIX password:\" ; send -- \"hogefuga\n\" ; expect \"Retype new UNIX password:\" ; send -- \"hogefuga\n\" ; expect \"passwd: password updated successfully\" ; send -- \"exit\n\""
